repos:
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types: [shell]
      - id: shfmt
        name: shfmt
        entry: shfmt
        language: system
        types: [shell]
